/**
 * Pixel-art persona portraits for Think Tank.
 *
 * Each persona is a 48x48 pixel map: every string is one row, every character
 * a palette key ("." = transparent, letting the backdrop show through).
 * `talk` holds replacement rows for the open-mouth frame used while streaming.
 * Rows are converted to <rect>s with horizontal runs of one colour merged.
 */

const SIZE = 48;

/** A persona's own 48x48 backdrop scene, drawn under the character layer. */
type BgDef = {
  palette: Record<string, string>;
  rows: string[];
};

type SpriteDef = {
  palette: Record<string, string>;
  bg: BgDef;
  rows: string[];
  talk: Record<number, string>;
};

// prettier-ignore
const DEVIL_BG: BgDef = {
  palette: {
    "a": "#07082a",
    "b": "#0c0a1c",
    "c": "#100c1e",
    "d": "#ffb020",
    "e": "#c8790a",
    "f": "#0a0f1c",
    "g": "#5c1414",
    "h": "#0d1042",
    "i": "#ff4b4b",
    "j": "#ff5a4a",
    "k": "#251d47",
    "l": "#1b1636",
    "m": "#ff2d3a",
    "n": "#7a1620",
    "o": "#ffb020",
    "p": "#4a1620",
    "q": "#2d0d13",
    "r": "#ff8a3d",
    "s": "#ffe37a",
  },
  rows: [
    "aaaaaabbbbbbbbbbcccccccccccccccbbbbbbbbbbbaaaaaa",
    "aaaaaaaadddeeaaacfggggggggggggcaaaaaaaaaaaaaaaaa",
    "aahhhhhhddddehhhcfgiiigiiigiiichhhhhhjhhhhhhhhaa",
    "aahhhhhhdeeedhhhcfgigggigigigichhhhhjjjhhhhhhhaa",
    "aahhhhhhdddddhhhcfgiiigigigigichhhhjjjjjhhhhhhaa",
    "aahhhhhhdddddhhhcfgggigigigigichhhhhhfhhhhhhhhaa",
    "aahhhhhhhhhhhhhhcfgiiigiiigiiichhhhhhjhhhhhhhhaa",
    "aahhhhhhhhhhhhhhccccccccccccccchhhhhhhhhhhhhhhaa",
    "aahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhaa",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "kmnonhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkmnon",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "knonmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhknonm",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "konmnhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkonmn",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "kllllhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkllll",
    "knmnohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhknmno",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kmnonppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkmnon",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "knonmppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppknonm",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "konmnppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkonmn",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "knmnoppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppknmno",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "kllllppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhpppkllll",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "qqqhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhqqq",
    "prphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhprp",
    "ppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhppp",
    "psrhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhrsp",
    "rpphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhppr",
    "ppphhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhppp",
    "pppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaappp",
    "pppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaappp",
  ],
};

// prettier-ignore
const TYSON_BG: BgDef = {
  palette: {
    "a": "#07082a",
    "b": "#7a3d18",
    "c": "#2a1030",
    "d": "#ff9b3d",
    "e": "#101142",
    "f": "#6fe3c1",
    "g": "#ff9b3d",
    "h": "#ff5a5f",
    "i": "#5ad0ff",
    "j": "#c7ccdd",
    "k": "#f7d046",
    "l": "#8a5a2c",
    "m": "#e8c99a",
    "n": "#1c1e30",
    "o": "#bfe8ff",
    "p": "#6fe3c1",
    "q": "#ff5a5f",
    "r": "#f7d046",
    "s": "#241a3a",
  },
  rows: [
    "aaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbcaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaabdddbdddbdddbdbdbddbbaaaaaaaaaaaaaa",
    "aaeeeeeeeeeeebdbbbdbdbbdbbdddbdbdbeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeebdbdbdddbbdbbdddbdbdbeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeebdbdbddbbbdbbdbdbdbdbeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeebdddbdbdbdddbdbdbddbbeeeeeeeeeeeeaa",
    "faeeeeeeeeeeebbbbbbbbbbbbbbbbbbbbceeeeeeeeegeeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeejeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeejjjeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeejjjeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeejjjeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelleeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllleeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllleeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeemmmmeeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeemmmmeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllleeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllleeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllleeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "knnnnnnnneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeai",
    "fnoopoooneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah",
    "inqoooroneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeak",
    "hnopooooneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "knnnnnnnneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeai",
    "fnnnnnnnneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah",
    "isssssssseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "kaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeai",
    "faeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah",
    "iaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeak",
    "haeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaf",
    "ssseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeesss",
    "aaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaa",
    "aaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  ],
};

// prettier-ignore
const BISON_BG: BgDef = {
  palette: {
    "a": "#07082a",
    "b": "#0c0c14",
    "c": "#160f10",
    "d": "#5c3312",
    "e": "#ff9b3d",
    "f": "#10134a",
    "g": "#8a5a2c",
    "h": "#6a4420",
    "i": "#9aa1b8",
    "j": "#9aa1b8",
    "k": "#eef1f8",
    "l": "#3a4058",
    "m": "#eef1f8",
    "n": "#f7d046",
    "o": "#6fe3c1",
    "p": "#a8743e",
    "q": "#ff5a5f",
    "r": "#5ad0ff",
    "s": "#d9a36a",
    "t": "#c7ccdd",
    "u": "#d9a36a",
    "v": "#8a5a2c",
  },
  rows: [
    "aaabccccdeeedededeeedeeedcccdeeedeeedcccccccbaaa",
    "aaabccccdedddededdeddededcccddedddeddcccccccbaaa",
    "aafbccccdeeedeeeddeddeeedccccdedcdedccccccccbfaa",
    "aafbccccdddedededdeddedddcccddedddedccccccccbfaa",
    "aafbccccdeeedededeeededcccccdeeeddedccccccccbfaa",
    "aafbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "haffffffffffffffffffffffffffffffffffffffffffffah",
    "giiiiiiiiiiffffffffffffffffffffffffffjjjjjjjjjag",
    "hiklklklkliffffffffffffffffffffffffffjmmmmmmmjah",
    "gilnnloolliffffffffffffffffffffffffffjmmmmmmmjag",
    "hiklklklkliffffffffffffffffffffffffffjmmmmmmmjah",
    "gilllllllliffffffffffffffffffffffffffpppppppppag",
    "hikqqlrrkliffffffffffffffffffffffffffsssssssssah",
    "gilllllllliffffffffffffffffffffffffffftfffffftag",
    "hikkkkkkkkifffffffffffffffffffffffffffftfffftfah",
    "giiiiiiiiiiffffffffffffffffffffffffffffftfftffag",
    "haffffffffffffffffffffffffffffffffffffffuuuuffah",
    "gaffffffffffffffffffffffffffffffffffffffvvvvffag",
    "haffffffffffffffffffffffffffffffffffffffuuuuffah",
    "gaffffffffffffffffffffffffffffffffffffffffffffag",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaffffffffffffffffffffffffffffffffffffffffffffaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  ],
};

// prettier-ignore
const ANSHU_BG: BgDef = {
  palette: {
    "a": "#07082a",
    "b": "#6fe3c1",
    "c": "#1a2856",
    "d": "#7a5a12",
    "e": "#c9fbee",
    "f": "#233d62",
    "g": "#f7d046",
    "h": "#c9fbee",
    "i": "#fff3c2",
    "j": "#10123f",
    "k": "#9fb3e6",
    "l": "#6fe3c1",
    "m": "#3fae8e",
    "n": "#1c1e34",
    "o": "#5a3a1e",
    "p": "#6fe3c1",
    "q": "#c9fbee",
    "r": "#3a2413",
    "s": "#c9fbee",
  },
  rows: [
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaabbbbbbbbaaaaaaaaaaaaaaaaaaaa",
    "aacddddddccccccccccbbbeeeebbbcccccccccccccccccaa",
    "aafdggggdfffffffffffbbbbbbbbffffffffffffffffffaa",
    "aafdggggdffffffffffffffhhfffffffffffffffffffffaa",
    "aafdiiiidffffffffffffhfhhfhfffffffffffffffffffaa",
    "aafdggggdffffffffffffffhhfffffffffffffffffffffaa",
    "aafdggggdfffffffffffffffffffffffffffffffffffffaa",
    "aajddddddjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkjaa",
    "aajjjjdjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajlljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aamjmjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnnnnnna",
    "amljomjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnppppna",
    "aamjmjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnpqqpna",
    "aajrojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnpnnpna",
    "aajrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnppppna",
    "aajrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnnnnnna",
    "aajrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnnnnnna",
    "aasrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnnnnnna",
    "aooooojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aarrrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsjjjjjaa",
    "aarrrjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsjjjjjjaa",
    "aajjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aakjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  ],
};

// prettier-ignore
const BUCKS_BG: BgDef = {
  palette: {
    "a": "#07082a",
    "b": "#f7d046",
    "c": "#100f3f",
    "d": "#c9fbee",
    "e": "#5c4712",
    "f": "#c7ccdd",
    "g": "#141225",
    "h": "#08140f",
    "i": "#c9fbee",
    "j": "#3ddc84",
    "k": "#ff9b3d",
    "l": "#ff4a6a",
    "m": "#fff3b0",
    "n": "#a67a12",
    "o": "#f7d046",
  },
  rows: [
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaccdcccccccccebbeecccccccccccccccccccccccccccaa",
    "aaccccccccccccebbbeccccccccccccccccccccfccccdcaa",
    "agggggggggggggeebbecccccccccccccccccccfffcccccaa",
    "aghhhhhihhhhhgebbbecccccccccccccccccccfffcccccaa",
    "aghhhhhjhhhhhgeeeeecccccccccccccccccccfffcccccaa",
    "aghhhihjhhhihgccccccccccccccccccccccccfffcccccaa",
    "aghhhjhjhhhjhgccccccccccccccccccccccccfffcccccaa",
    "aghihjhjhihjhgcccccccccccccccccccccccckckcccccaa",
    "aghlhjhjhlhjhgccccccccccccccccccccccccckccccccaa",
    "aghlhjhjhlhjhgccccccccccccccccccccccccccccccccaa",
    "aghlhjhjhlhjhgccccccccccccccccccccccccccccccccaa",
    "aghhhhhhhhhhhgccccccccccccccccccccccccccccccccaa",
    "agggggggggggggccccccccccccccccccccccccccccccccaa",
    "aacccccccccccccccccccccccccccccccccccccmmmmmccaa",
    "aacccccccccccccccccccccccccccccccccccccnnnnnccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccmmmmmmccaa",
    "aaccccccccccccccccccccccccccccccccccccnnnnnnccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccmmmmmmmcaa",
    "aaccccccccccccccccccccccccccccccccccccnnnnnnncaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aacccccccccccccccccccccccccccccccccccmmmmmmmmcaa",
    "aacccccccccccccccccccccccccccccccccccnnnnnnnncaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aacccccccccccccccccccccccccccccccccccccccccccoaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaocccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aacoccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaccccccccccccccccccccccccccccccccccccccccccccaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  ],
};

// prettier-ignore
const DEVIL: SpriteDef = {
  palette: {
    k: "#2a0710",
    R: "#e8363f",
    r: "#a81c2c",
    q: "#6a0d1c",
    S: "#ff7d6e",
    h: "#fff3da",
    H: "#e6c894",
    j: "#a9804f",
    J: "#6e4a2c",
    b: "#1a0509",
    B: "#4f1c2c",
    Y: "#fff27a",
    y: "#f59a1c",
    w: "#fffbe8",
    t: "#ff5a5f",
    C: "#2a1a3e",
    c: "#48356a",
    L: "#ff5a5f",
    l: "#b8283a",
    G: "#ffd24a",
  },
  bg: DEVIL_BG,
  rows: [
    "................................................",
    ".....kk..................................kk.....",
    "....kHHk................................kHHk....",
    "....kHHk................................kHHk....",
    "....kHHk................................kHHk....",
    "....kHHjk..............................kjHHk....",
    ".....khHjk............................kjHhk.....",
    ".....khhHjkk........kkkkkkkk........kkjHhhk.....",
    ".....kHhhHHHkkkk..kkbbbbbbbbkk..kkkkHHHhhHk.....",
    "......kHhhHHHHHHkkbBBBBBBBBBBbkkHHHHHHhhHk......",
    "......kHHhhhHHHHHBBBBbbbbbbbbBBHHHHHhhhHHk......",
    ".......kHHHhhhHHjbBbbbbbbbbbbbbjHHhhhHHHk.......",
    "......kkkHJJJJJbBbbbbbbbbbbbbbbbBJJJJJHkkk......",
    ".....kRSkkHHHJbBRSRRRRbbbbRRRRRrbbJHHHkkSRk.....",
    "......kRSkkHHHRRRSRRRRbbbbRRRRRRrbHHHkkSRk......",
    "......kRRRRkkHbbSRRRRRRbbRRRRRRRbbbkkRRRRk......",
    "......kRRrRRRkRbbbRRRRRRRRRRRRbbbrkRRRrRRk......",
    "......kRRrrRRRRRRbbbRRRRRRRRbbbRRrrRRrrRRk......",
    ".......kRrrrRRRRRRRbbbRRRRbbbRRRRrrRrrrRk.......",
    ".......kRRrrRrRRkkkkkbbRRbbkkkkkRrrRrrRRk.......",
    ".......kRRrrRkRRyYYbYykRRkyYbYYyrrkRrrRRk.......",
    "..k.....kRRrRkRRRyYbyRRrRRRybYyRrrkRrRRk.....k..",
    ".klkk....kRRRkRRRrrrrRRrSRRrrrrRrrkRRRk....kklk.",
    ".kLllk....kkRkrrRRRRRRrRRRRRRRRRrrkRkk....kllLk.",
    ".kLlllk.....k.kRrRRRRRqqRqqRRRRrqk.k.....klllLk.",
    "..kLlllkk.....kRrRRRRRRRRRRRRkRrqk.....kklllLk..",
    "..kLlLLllk....krRrRRRRRRRRRkkRrqqk....kllLLlLk..",
    "..kLLlLLllk....krRrrkkkkkkkwRrqqk....kllLLlLLk..",
    "..kLLLlLLllk....krRRRrrrRRwRRqqk....kllLLlLLLk..",
    "..kLLLLlLLllk....krRbbbbbbbRqqk....kllLLlLLLLk..",
    "...kLLLlLLLllk....krRbbbbbbqqk....kllLLLlLLLk...",
    "...kLLLLlLLLllk....kqbbBbbbqk....kllLLLlLLLLk...",
    "...kLLLLLlLLllk....krbbBbbqqk....kllLLlLLLLLk...",
    "...kLLLLLlLLLllk...krrbbbbqqk...kllLLLlLLLLLk...",
    "...kLLLLLLlLLLllk..krrbbBbqqk..kllLLLlLLLLLLk...",
    "...kLLLLLLlLLLllkkkkrrbbbbrrkkkkllLLLlLLLLLLk...",
    "...kLLLLLLLlLLCCCCCbrrrbbrrrbCCCCCLLlLLLLLLLk...",
    "...kLLLLLLLlLCCCCCCbbbbbbbbbbCCCCCCLlLLLLLLLk...",
    "...kLLLLLLCCCcCCcCCCbbbbbbbbCCCcCCCCCCLLLLLLk...",
    "...kLLLLCCCCccCCCcCCbbbLLlbbCCcCCCCCCCCCLLLLk...",
    "..kLLLLCCCccccCCCcCCCbbLLlbCCCcCCCCCCCCCCLLLLk..",
    "..kLLLCCCccccCCCCCcCCbbLLlbCCcCCCCCCCCCCCCLLLk..",
    "..kLLLCCccccCCCwGCCcCCLLLlCCcCCCCCCCCCCCCCLLLk..",
    "..kLLLCCCccCCCCGGCCcCCLLLlCCcCCCCCCCCCCCCCLLLk..",
    "..kLLCCCCCCCCCCCCCCCcCLLLLCcCCCCCCCCCCCCCCCLLk..",
    ".kLLLCCCCCCCCCCCCCCCcCCLLCCcCCCCCCCCCCCCCCCLLLk.",
    ".kLLLCCCCCCCCCCCCCCCCcCLlCcCCCCCCCCCCCCCCCCLLLk.",
    ".kLLCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCLLk.",
  ],
  talk: {
    25: "..kLlllkk.....kRrRRRRRRRRRRRRRRrqk.....kklllLk..",
    26: "..kLlLLllk....krRrRkkkkkkkkwkRrqqk....kllLLlLk..",
    27: "..kLLlLLllk....krRrrkqwqqqqwkrqqk....kllLLlLLk..",
    28: "..kLLLlLLllk....krRRkqwqqqqwkqqk....kllLLlLLLk..",
    29: "..kLLLLlLLllk....krRRkktttkkqqk....kllLLlLLLLk..",
    30: "...kLLLlLLLllk....krbbbbbbbqqk....kllLLLlLLLk...",
    31: "...kLLLLlLLLllk....kqbbbbbbqk....kllLLLlLLLLk...",
    32: "...kLLLLLlLLllk....krbbBbbbqk....kllLLlLLLLLk...",
    33: "...kLLLLLlLLLllk...krbbBbbqqk...kllLLLlLLLLLk...",
    34: "...kLLLLLLlLLLllk..krrbbbbqqk..kllLLLlLLLLLLk...",
    35: "...kLLLLLLlLLLllkkkkrrbbBbrrkkkkllLLLlLLLLLLk...",
    36: "...kLLLLLLLlLLCCCCCbrrbbbbrrbCCCCCLLlLLLLLLLk...",
    39: "...kLLLLCCCCccCCCcCCbbbbblbbCCcCCCCCCCCCLLLLk...",
  },
};

// prettier-ignore
const TYSON: SpriteDef = {
  palette: {
    k: "#1c0c05",
    O: "#f5902c",
    o: "#c45e16",
    P: "#ffc06a",
    s: "#231009",
    W: "#fff7ea",
    w: "#e2cbb0",
    N: "#ec7a86",
    n: "#a83e50",
    E: "#c2f060",
    e: "#5d9a24",
    A: "#eceef6",
    a: "#a5aabd",
    D: "#5d6278",
    c: "#26283a",
    T: "#ff9b3d",
    G: "#6c7188",
    g: "#474b5f",
    f: "#1d1f30",
    V: "#9398b0",
    d: "#fff7ea",
    m: "#6b2a2a",
  },
  bg: TYSON_BG,
  rows: [
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    ".........kkkkk....................kkkkk.........",
    "........ksssssk..................ksssssk........",
    ".......ksOOOOOskkkkkkkkkkkkkkkkkksOOOOOsk.......",
    ".......ksOOOOOOsAAAAAADDDDAAAAAAsOOOOOOsk.......",
    ".......ksOOwwwOOAAAAaaaAAaaaAAAAOOwwwOOsk.......",
    ".......kOOOwWwOOaaaaPPOssOOOaaaaOOwWwOOOk.......",
    ".......kOOOwWwOkOOPsOOOssOOOsOOokOwWwOOOk.......",
    "........kOOOwOkOOPOOsOOssOOsOOOOokOwOOOk........",
    ".........kAAakOOssOOsOOssOOsOOssOokaAAk.........",
    "........kAAAkOOOOOsOOsOOOOsOsssOOOokAAAk........",
    "........kAAaOOOOOOOOOOOOOOOsOOOsOOOoaAAk........",
    "........kAAkOOOOOOOOOOOOOOOOOOOOOOOokAAk........",
    ".......kAAAAccOOWWWWWOOOOOOWWWWWOOccAAAAk.......",
    "......kAAAAAacckkkkkkkOOOOkkkkkkkccaAAAAAk......",
    "......kATTTAAccOeEEEkEkOOkEEEEEkOccAATTTAk......",
    ".....kAATPTAAaccOeEEkOOOOOOEEEekccaAATPTAAk.....",
    ".....kAATPTAAaccOOOOOOOOOOOOOOOOccaAATPTAAk.....",
    ".....kAATTTAAaccOOOOOOOOOOOOOOOOccaAATTTAAk.....",
    ".....kDATTTAaDccOOOOOONWNnOOOOOOccDaATTTADk.....",
    "......kATTTAaccOOOWWWWNNNnWWWwOOOccaATTTAk......",
    "......kDAAAaDccOOWWWWWWNnWWWWWwOOccDaAAADk......",
    ".......kDDDDccOOOWWWWWWkkWWWWWwOOOccDDDDk.......",
    ".......kOOOssOOOOWWwWWWWkWWWwWkOOOOssOOok.......",
    "......koossOOOOOOwwWkWkkkkWwkkwOOOOOOssook......",
    ".......kkkOOOOOOOOwwWkWWWWkkwwOOOOOOOokkk.......",
    ".........kOOOooooOOOwWWWWWWwOOOooooOOok.........",
    ".........koookGGGooOOwWWWWwOOooGGGkoook.........",
    "..........kkGGGGGggooowwwwoooggGGGGGkk..........",
    ".........kGGGGGggggggggggggggggggGGGGGk.........",
    ".........kGGGGGffffffffffffffffffGGGGGk.........",
    "........kGGGGGGffffffffffffffffffGGGGGGk........",
    ".......kkGGGGGGGGffffffffffffffGGGGGGGGkk.......",
    "......kGGGggGGGGGGGdGffffffGGdGGGGGGggGGGk......",
    ".....kGGGVVVggGGGGGdGGGGGGGGGdGGGGggGGGGGGk.....",
    "....kGGGVVVGGGggggGdGGGGGGGGGdggggGGGGGGGGk.....",
    "....kGGVVVGGGGGGGGgdggggggggdgGGGGGGGGGGGGGk....",
    "....kGVVVGGGGGGGGGGdGGGGgGGGdGGGGGGGGGGGGGGk....",
    "...kGGGVGGGGGGGGGGGdGGGGgGGGdGGGGGGGGGGGGGGk....",
    "...kGGGGGGGGGGGGGGGdGGGGgGGGaGGGGGGGGGGGGGGGk...",
    "...kGGGGGGGGGGGGGGGaGGGGgGGGGGGGGGGGGGGGGGGGk...",
    "..kGGGGGGGGGGGGgggggggggggggggggggGGGGGGGGGGk...",
    "..kGGGGGGGGGGGGGGGGGGGGGgGGGGGGGGGGGGGGGGGGGGk..",
  ],
  talk: {
    30: ".......kkkOOOOOOOOwwWWmmmmmmWwOOOOOOOokkk.......",
    31: ".........kOOOooooOOOwmmmmmmmmOOooooOOok.........",
    32: ".........koookGGGooOOkkNNNmkOooGGGkoook.........",
    33: "..........kkGGGGGggooowkkkkooggGGGGGkk..........",
  },
};

// prettier-ignore
const BISON: SpriteDef = {
  palette: {
    k: "#1c0d05",
    F: "#86522c",
    f: "#5a3319",
    q: "#3a1f0e",
    Q: "#b0733f",
    T: "#ecc792",
    t: "#c49058",
    I: "#f6ead0",
    i: "#c9b184",
    m: "#8a7148",
    E: "#ffffff",
    e: "#ff4a3a",
    Y: "#ffd84a",
    y: "#b8861c",
    J: "#d9a36a",
    j: "#a8743e",
    h: "#f2c996",
    Z: "#3b2413",
    z: "#fff3dc",
    p: "#e0606a",
  },
  bg: BISON_BG,
  rows: [
    "...k........................................k...",
    "..kIk......................................kIk..",
    ".kIIk......................................kIIk.",
    ".kIIk......................................kIIk.",
    ".kIIk..............kkkkkkkkkk..............kIIk.",
    ".kIIik............kqqqqqqqqqqk............kiIIk.",
    ".kIIiIkkkkkkkkkk.kqqfqfqqfqqfqk.kkkkkkkkkkIiIIk.",
    "..kIiiIIIImmmmmmkqqfqqqfqqfqqqqkmmmmmmIIIIiiIk..",
    "..kIiiIIIIiiiiiiIqqqqqqqqqqqqqqIiiiiiiIIIIiiIk..",
    "...kIiiiIImmmmmmIqqqqffqqqffqqqImmmmmmIIiiiIk...",
    "....kIiiiimmmmmmFFqfqqqqfqqqqqffmmmmmmiiiiIk....",
    ".....kIiiimmmmmzzzzzzzzzzzzzzzzhhmmmmmiiiIk.....",
    "......kkkimmmmJJJJJJJJJJJJJJJJJJhhmmmmikkk......",
    "....kkkkkkkkkkzzzzzzzzzzzzzzzzzzhhkkkkkkkkkk....",
    "...kFFFFFFFFFkFFFFFFFFFFFFFFFFFFffkFFFFFFFFFk...",
    "...kFFttttttFkFQQQFFFFFFFFFFFFQQQfkFttttttFFk...",
    "...kFFttttttFkFqqqQQQQFFFFQQQQqqqfkFttttttFFk...",
    "...kffFFFFFFFkFqqqqqqqFFFFqqqqqqqfkFFFFFFFffk...",
    "....kkffkkkkkkFFFkkEekFFFFkeEkkFffkkkkkkffkk....",
    "......kk.....kFFFFkkkFFFFFFkkkFFffk.....kk......",
    ".............kFFFfffffFFFFfffffFffk.............",
    ".............kFFFFTTEETTTTTTTtFFffk.............",
    ".............kFFFTEETTTTTTTTTTtFffk.............",
    ".............kFTTETTTTTttTTTTTTTtfk.............",
    ".............kFTTTttTTTttTTTttTTtfk.............",
    ".............kTTTTqqTTTTTTTTqqTTTtk.............",
    ".............ktTTTqqqTTTTTTqqqTTTtk.............",
    ".............ktTTTTqqTYTTYTqqTTTTtk.............",
    "...........kkFFttTTTTTYTTyTTTTTttFFkk...........",
    "........kkkFQQQtttTTTTTYyTTTTTtttQQQFkkk........",
    "......kkFFQQFFFFFtqqttttttttqqqFFFFFQQFFkk......",
    "....kkFFFFFFFFFFFFttqqqqqqqqttFFFFFFFFFFFFk.....",
    "..kkFFFFFFFFFFFFZFFfFFFFFFFFfFFFZFFFFFFFFFFkkk..",
    "kkFFQQQQQFFFZzJJzZffffffffffffffzJzZFFFQQQQQFFkk",
    "FFQQFFFFFFFFZzJJhZfffffffffffffZzJzZFFFFFFFFQQFF",
    "FQFFFFFFFFFZzJJJJzZfffffffffffjzJJJzZFFFFFFFFFQF",
    "FFFFFFFFFFFZzJJJJhZffffffffffFZzJJJzZFFFFFFFFFFF",
    "FFFFFFFFFFFZzJJJJJzZffffffffFjzJJJJzZFFFFFFFFFFF",
    "FFFFFFFFFFFZzJJJJJJzZFFFFFFFZZzJJJJzZFFFFFFFFFFF",
    "FFFFFFFFFFZzJJJJJJJzzZZFFjZZzzJJJJJJzZFFFFFFFFFF",
    "FFFFFFFFFFZzJJJJJJJJJzzZZZzzJJJJJJJJzZFFFFFFFFFF",
    "FFFFFFFFFFZzJJJJJJJJJJJzzzJJJJJJJJJJzZFFFFFFFFFF",
    "fFFFFFFFFfZzJJJJJjJZZZZJJZZZZJJjJJJJzZfFFFFFFFFf",
    "FfFFFFFFFfZzJJJjjJJJzzZzJJzzZzJJjjJJzZfFFFFFFFfF",
    "FFfFFFFFFZzJJJjJJJJZZZZzJJZZZzJJJJjJJzZFFFFFFfFF",
    "FFFfFFFFFZzJJJJJJJJZzzzzJJJzZzJJJJJJJzZFFFFFfFFF",
    "FFFFFFFFFZzJJJJJJJJZZZZJJZZZZzJJJJJJJzZFFFFFFFFF",
    "FFFFFFFFFZzJJJJJJJJJzzzzJJzzzzJJJJJJJzZFFFFFFFFF",
  ],
  talk: {
    29: "........kkkFQQQtttqqqqqYyqqqqqtttQQQFkkk........",
    30: "......kkFFQQFFFFFtqEEqqqqqqqEEtFFFFFQQFFkk......",
    31: "....kkFFFFFFFFFFFFtqqqqqqqqqqtFFFFFFFFFFFFk.....",
    32: "..kkFFFFFFFFFFFFZFFqqqpppppqfFFFZFFFFFFFFFFkkk..",
  },
};

// prettier-ignore
const ANSHU: SpriteDef = {
  palette: {
    k: "#24100a",
    X: "#e06a2c",
    x: "#a8441a",
    Z: "#ffa259",
    C: "#fbeedb",
    c: "#d9c3a0",
    D: "#3a1a12",
    B: "#ffffff",
    b: "#cfd4e8",
    v: "#9aa0c0",
    M: "#6fe3c1",
    m: "#35a88a",
    u: "#1f6b5e",
    U: "#c2f7e6",
    W: "#6e3a1c",
    w: "#c07a48",
    n: "#2a120a",
    p: "#e87a86",
  },
  bg: ANSHU_BG,
  rows: [
    ".......kk..............................kk.......",
    "......kDDk............................kDDk......",
    ".......kDDkk........................kkDDk.......",
    ".......kDDDDk......................kDDDDk.......",
    "........kDXXXkk..................kkXXXDk........",
    "........kXCXXXXkk..............kkXXXXCXk........",
    "........kXCCCXXXXk..kkkkkkkk..kXXXXCCCXk........",
    ".........kXCCCXXXXkkXXXXXXXxkkXXXXCCCXk.........",
    ".........kXcCCCCXXXZZXXXXXXXXxXXCCCCcXk.........",
    "..........kXcCCCXXZXXXXXXXXXXXXxCCCcXk..........",
    "..........kXcCXXXZXXXXXXXXXXXXXXxXCcXk..........",
    "..........kXXXXXXXXXXXXUMXXXXXXXXxXXXk..........",
    "...........kXkXXXXXXXXXMMXXXXXXXXxkXk...........",
    "............kXXXXXXXXXXMmXXXXXXXXXxk............",
    "............kXXXXBBBBBXXXXBBBBBXXXxk............",
    "............kXXBBBBXXXXXXXXXXBBBBXxk............",
    "...........kXXBbbXXXXXXXXXXXXXXbbBxk............",
    "...........kXBBXXXXXXXXXXXXXXXXXXBBxk...........",
    "...........kBbXXkCCCkXXXXXXkCCCkXXbBk...........",
    "..........kBbXCCCkkkCXXXXXXCkkkCCCXbBk..........",
    ".........kBbCCCCCcccCCCXXCCCcccCCCCCbBk.........",
    ".........kBkXXCCCCCCCCCCCCCCCCCCCCXxkBk.........",
    "........kBk.kkXCCCCCCCCCCCCCCCCCCxkk.kBk........",
    ".........k....kkXCCCCCnbnnCCCCCxkk....k.........",
    "..............kkkXCCCCCnnCCCCCxkkk..............",
    "...........kkkBBBkCCCCCCCCCCCCkBBBkkk...........",
    ".........kkBBBkkkkXCCkCCCCkCCk.kkkBBBkk.........",
    "........kBBkkkkkbkBcCCkkkkCCcbkbkkkkkBBk........",
    ".......kBkk..kbbkkBBccccccccBbkkbbk..kkBk.......",
    "........k...kbkk.kBBBBBBBBBBBbk.kkbk...k........",
    ".............k...kBBBBBBBBBBBbk...k.............",
    ".................kBBBBBBBBBBBbk.................",
    "............kkkkkkBBBBbBBBbBBbkkkkkk............",
    "...........kkkuuuuCBBBbBBBbBbCuuuukkk...........",
    ".........kkkwWkmuuuBBBbBBBvBbuuuukwWkkk.........",
    ".......kkMMkWWkumuuBBBBbBbBBbuuuMkWWkMMkk.......",
    "......kMMMUMkkMMmuuuBBBbBbBbuuuMMMkkMMMMMk......",
    ".....kMMMUUkwWkMumuuBBBbBbBbuuuMMkwWkMMMMMk.....",
    "....kMMMUUUkWWkMMmuuBBBbBBBbuuMMMkWWkMMMMMMk....",
    "....kMMUUUMMkkMMMumuuBBBBBbuuMMMMMkkMMMMMMMk....",
    "...kMMUUUMMMMkkMMuumuBBBvBbuMMMMMkkMMMMMMMMMk...",
    "...kMUUUUMMMkwWkMMumuuBBvbuuMMMMkwWkMMMMMMMMk...",
    "...kMUUUMMMMkWWkMMuumuBBBbuMMMMMkWWkMMMMMMMMk...",
    "..kMMMUMMMMmMkkkkMMumuuBbuMMMMMkkkkMmMMMMMMMMk..",
    "..kMMMMMMMMmMMkwWkMuumukkMMMMMkwWkMMmMMMMMMMMk..",
    "..kMMMMMMMmMMMkWWkkkumkUMkMMkkkWWkMMMmMMMMMMMk..",
    ".kMMMMMMMMmMMMMkkkwWkukMMkMkwWkkkMMMMmMMMMMMMMk.",
    ".kMMMMMMMmMMMMMMMkWWkukkkkMkWWkMMMMMMMmMMMMMMMk.",
  ],
  talk: {
    26: ".........kkBBBkkkkXCCCkkkkCCCk.kkkBBBkk.........",
    27: "........kBBkkkkkbkkcCCkppkCCckkbkkkkkBBk........",
    28: ".......kBkk..kbbkkBCccckkcccCbkkbbk..kkBk.......",
    29: "........k...kbkk.kBBCCCCCCCCBbk.kkbk...k........",
  },
};

// prettier-ignore
const BUCKS: SpriteDef = {
  palette: {
    k: "#1a0c06",
    U: "#7a4a2a",
    u: "#4e2d18",
    V: "#a06a40",
    S: "#f0c09a",
    s: "#c98e66",
    t: "#ffe0c4",
    L: "#14121c",
    l: "#3b3d5c",
    i: "#ffffff",
    G: "#f7d046",
    g: "#c78f1e",
    d: "#7a4c0c",
    Y: "#fff5b0",
    R: "#6a2fa0",
    r: "#43196a",
    Q: "#9255cc",
    m: "#5a1e1e",
    e: "#ff4a6a",
    a: "#5ad0ff",
  },
  bg: BUCKS_BG,
  rows: [
    "................................................",
    "................................................",
    "................................................",
    "...............................k................",
    "...........................k..kGk...............",
    "..........................kGk.kGGk.k............",
    "..........................kYGkGGGkkGk...........",
    ".........................kGYGGGGGkGGk...........",
    "...................kkkkkkkGGYGGGGGGGk...........",
    "..................kUUUUUUUGGGGeeGGGGk...........",
    "................kkVVUUUUUUgddddggaggk...........",
    "...............kUVUUUUUUUUUggggdddddk...........",
    "..............kUVUUUUUUUUUUUUUUuukkk............",
    "..............kUUUUUUUUUUUUUUUuuuk..............",
    ".............kUUUUUSUUUUUUUUuuUUuuk.............",
    ".......kkkk.kUUUSuuuSSSUUSSuSSSsUuuk.kkkk.......",
    ".....kkUUUUkkUUuuSSSuuSSSSSSSSSSsuukkUUUUkk.....",
    "....kUUUUUUUUUUSSSSSSSSSSSSSSSSSsuuUUUUUUUUk....",
    "....kUUUSSSUGGYGGGGGGGGGGGGGGGGGGYGGUSSSUUUk....",
    "...kUUUSSSSGUUGLilLLLGggggGLLilLLGuUGSSSSUUUk...",
    "...kUUUSSsssSUGLlLLLLGSSSSGLLlLLLGuSsssSSUUUk...",
    "...kUUUSSsssSUGLLLLLLGSSSSGLLLLLLGuSsssSSUUUk...",
    "...kUUUSSsssUUUGGGGGGSSSSSSGGGGGGuuUsssSSUUUk...",
    "....kUUSSssSUUUUsSSSSSSSSSSSSSSsUuuUSssSSUUk....",
    "....kUUUUSSUUUUUUSSSSSSttSSSSSsUUuuUUSSUUUiak...",
    "....kGkUUUUkkkUUSSSSSSuSSuSSSSSsuukkkUUUUkaak...",
    "...kYk.kkkk..kUSSSSSSSSSSSSSSSSSsuk..kkkk.kk....",
    "...kgkkGk....kUSSSSSSSSSSSSkkkkSsuk.............",
    "...kGkkGk.....kSSSkkkkkkkkkGYkSSsk..............",
    "....kgGk......ksSSSkYYgadddddkSSsk..............",
    ".....kk........ksSSkkdddGgkkkSSsk...............",
    "................ksSSSkkkkkSSSSsk................",
    ".................kssSSSSSSSSssk.................",
    ".............kkkkkuussssssssuukkkkk.............",
    "............krrYrUuuuuuuuuuuuuUrrGrk............",
    "..........kkRYQdgGUUUUUUUUUUUUrYgdrGkk..........",
    ".........kRYRdgQgdgYgUUUUUUUgGgdgrgdRGk.........",
    ".......kkRRdgRgGrrgdgGgYgGgYgdgrQYgRgdRkk.......",
    "......kRRRQQgRRdgrrUUdgdgdgdUrrQgdRRgRRRRk......",
    ".....kRRRYQQRGRrgYgrUUUUUUUUrrgGgRRYRRYRRRk.....",
    "....kRRRYQQRRdgRrdgGgUUUUUUUgYgdRRgdRRRYRRk.....",
    "....kRRQYQRRRRgYrrQdgYgGgYgGgdrrRGgRRRRYRRRk....",
    "....kRQYQRRRRRRdgGQrrdGGdGgdrQrYgdRRRRRRYRRk....",
    "...kRRYQRRRRRRRRgdgQrGYGddgrQrgdgRRRRRRRRYRk....",
    "...kRYRRRRRRRRRRRrgYgGGddGGrgGgRRRRRRRRRRRYRk...",
    "...kRYRRRRRRRRRRRRrdGGGGdGgggdRRRRRRRRRRRRYRk...",
    "..kRYRRRRRRRRRRRRRrrrGGGddgdrrRRRRRRRRRRRRRYk...",
    "..kRRRRRRRRRRRRRRRRrrggdgggrrRRRRRRRRRRRRRRRRk..",
  ],
  talk: {
    28: "...kGkkGk.....kSSSkkkkkkkkkGYGkSsk..............",
    29: "....kgGk......ksSSkGYGGaYGGmmkSSsk..............",
    30: ".....kk........kSSkmmmmmmmmmmkSsk...............",
    31: "...............ksSSkmmmmmmmmmkSsk...............",
    32: "................ksSkmmmmmmmmkSsk................",
    33: ".............kkkkksSkkGGGGkkSskkkkk.............",
    34: "............krrYrUussskkkksssuUrrGrk............",
  },
};

const SPRITES: Record<string, SpriteDef> = {
  devil: DEVIL,
  tyson: TYSON,
  bison: BISON,
  anshu: ANSHU,
  bucks: BUCKS,
};

type Run = { x: number; y: number; w: number; fill: string };

function pushRuns(out: Run[], rows: readonly string[], palette: Record<string, string>): void {
  for (let y = 0; y < rows.length; y++) {
    const row = rows[y];
    let x = 0;
    while (x < row.length) {
      const key = row[x];
      let end = x + 1;
      while (end < row.length && row[end] === key) end++;
      const fill = palette[key];
      if (fill) out.push({ x, y, w: end - x, fill });
      x = end;
    }
  }
}

const cache = new Map<string, Run[]>();

function spriteRuns(id: string, talking: boolean): Run[] {
  const cacheKey = `${id}:${talking ? 1 : 0}`;
  const hit = cache.get(cacheKey);
  if (hit) return hit;
  const def = SPRITES[id];
  const runs: Run[] = [];
  pushRuns(runs, def.bg.rows, def.bg.palette);
  const rows = talking ? def.rows.map((row, i) => def.talk[i] ?? row) : def.rows;
  pushRuns(runs, rows, def.palette);
  cache.set(cacheKey, runs);
  return runs;
}

export function PersonaSprite(props: { name: string; talking?: boolean; className?: string }): JSX.Element {
  const { name, talking = false, className } = props;
  const lookup = name.trim().toLowerCase();
  const id = lookup in SPRITES ? lookup : "devil";
  const runs = spriteRuns(id, talking);
  return (
    <svg
      className={className}
      role="img"
      aria-label={`${name} portrait`}
      viewBox={`0 0 ${SIZE} ${SIZE}`}
      width="100%"
      height="100%"
      shapeRendering="crispEdges"
      style={{ imageRendering: "pixelated" }}
    >
      {runs.map((r, i) => (
        <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.fill} />
      ))}
    </svg>
  );
}
